# Generated by Django 3.2.6 on 2021-08-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_post_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Post',
            new_name='post',
        ),
    ]
